# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd -- info on anchors and mappings
# &label creates an anchor
# *label substitutes the anchors content
# <<: is a special key that will merge a map provided in an anchor with the following items

env:
    global:
        - CONAN_DOCKER_ENTRY_SCRIPT=./docker-entry-script

anchors:
    linux: &linux
        os: linux
        DIST: xenial
        language: python
        python: "2.7"
        services:
            - docker

    osx: &osx
        os: osx
        language: generic

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
        #- <<: *linux
        #  env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
        #- <<: *linux
        #  env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
        #- <<: *linux
        #  env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
        #- <<: *linux
        #  env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
        #- <<: *osx
        #  osx_image: xcode9.4
        #  env: CONAN_APPLE_CLANG_VERSIONS=9.1
        #- <<: *osx
        #  osx_image: xcode10.1
        #  env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh
  - conan remote add extcpp https://api.bintray.com/conan/ext/cpp --insert

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh

