#!/bin/bash

echo "#################################################"
echo "#################################################"
echo "hello from inside of the container"

if type apt &>/dev/null; then
    sudo apt-get update
    sudo apt-get remove --purge -y ghc
    sudo apt-get install -y python2.7
fi

echo "#################################################"
echo "#################################################"
